<?php require('template/header.phtml') ?>
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
            <?php foreach ($view->values as $value)
            echo '<h1 id="listHeader">
                <strong>'.$value->getTitle().'</strong>
                <span class="headerPrice">'.$value->getCurrency().$value->getPrice().'</span>
            </h1>
           
            <div>
                <strong class="publishDate">Publish Date: </strong>
                '.$value->getDate().'
            </div>
            <div>
                <strong class="publishLocation">Location: </strong>
                '.$value->getCountry().','.$value->getState().'
            </div>
             
            <div class="itemImg">
                <img class="img-responsive" src=images/advertImg/'.$value->getImg().'>
            </div>
            <!--For this section I want to add the description, available sizes, color and add to watchList-->
            <div class="usefulInfo">
                <h3>Useful Information</h3>
                <p>'.$value->getDescription().'</p>

            </div>';
             ?>

        </div>

        <?php if ($view->doHide === true) : ?>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <div class="bg-success lead text-center">This product is listed as yours hence no contact details required</div>
            </div>
        <?php elseif (isset($_SESSION['logged_in']) == false):?>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 alert-warning lead">LogIn/Register to view contact details of seller</div>

        <?php endif; ?>
        <?php if( $view->doHide === "" && isset($_SESSION['logged_in']) === true):?>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <div id="contactHeader">
                    <h2 class="lead">Contact Publisher</h2>
                    <?php foreach ($view->values as $value)
                        echo ' <p><b>Seller Name:</b> '.$value->getfName().'</p>
                                  <p><b>Seller Email:</b>'.$value->getEmail().'</p>
                                  <p><b>Seller Mobile No:</b>(44+).'.$value->getPhoneNo().'</p>'

                    ?>
                </div>
            </div>
        <?php endif;?>
    </div>
</div>

<?php require('template/footer.phtml') ?>
