<?php require('template/header.phtml') ?>
<div class="row info">
<h2>How it works </h2>
    <div class="col-sm-4">
        <img src="images/websiteImg/register.png" class="icon">
        <h4>Register</h4>
    </div>
    <div class="col-sm-4">
        <img src="images/websiteImg/logIn.png" class="icon">
        <h4>LogIn</h4>
    </div>
    <div class="col-sm-4">
        <img src="images/websiteImg/megaphone.png" class="icon">
        <h4>Advertise</h4>
    </div>
</div>
<div class="container">
    <div class="row" id="moreInfo">
        <div class="col-md-6">
            <img src="images/websiteImg/view.png" class="img-responsive">
        </div>
        <div class="col-md-6 text-justify">
            <h4>Here is a little history of MallFromAfrica</h4>
            <p>
                MallFromAfrica is dedicated to making available goods unique to Africa to interested buyers in the
                Uk. It is a platform that connects indigenous African brands to their loyal fans in diaspora. MallFromAfrica
                was conceptualized by a young African Woman in her second year Studying Bsc Software Engineering. The idea first came to mind
                while watching a seasonal called insecure.</p>
            <p>One of the lead actors Issa Rae had a style that was very intriguing and the founder
                thought to herself if only there was a place where all things african was sold and was easily accessible at a cheaper rate.
                She discussed this idea with a couple of friends and later entered into a competition at her University for tech start-ups to see
                if the idea could be actualized. That was one step to the numerous steps taken to actualize this dream.
            </p>

        </div>
    </div>
</div>
<div class="container-fluid info">
<div class="row">
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 text-justify">
        <p class="greyTextArea">If you are looking for a site that sells all things african, MallFromAfrica
        allows you to shop directly from Africa and gets it delivered to your doorstep. No more
        waiting for the aunt to come back from travels. Why don't you try an easier, safe, flexible way to
        get those items that scream african to your doorstep</p>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <img src="images/websiteImg/cart.png">
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 text-justify">
        <p class="greyTextArea">If you are a brand in an African country and would like to expand your market
        beyond the borders of your country you can place your advert on this site for your item, depending on if
        you are a certified brand back home and have good ratings from customers to place adverts please sign up</p>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <img src="images/websiteImg/africa.png">
    </div>

</div>
</div>


<?php require('template/footer.phtml') ?>
