<?php require('template/header.phtml') ?>
<div class="container">
        <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
            <?php if (isset($_SESSION['errorM'])) : ?>
                <div class="bg-success lead text-center"><?php  echo $_SESSION['errorM'];
                    unset($_SESSION['errorM']) ?></div>
            <?php endif; ?>
            <div class="row listing">
            <?php  foreach ($view->results as $results){ ?>
                <div class="listing-card col-sm-4">
                    <div class="card">
                        <div class="card-block">
                            <img class="card-img-top" alt="Card image cap" src=images/<?php echo $results->getImg();?>>
                            <a href="aboutListing.php?item=<?php echo $results->getProductId();?>"><h3 class="card-title"><?php echo $results->getTitle();?></h3></a>
                            <p class="card-text"><?php echo $results->getDescription();?></p>
                            <div class="row">
                                <div class="col-md-6">
                                   <span class="price"><?php echo $results->getCurrency();?><?php echo $results->getPrice();?></span>
                                </div>
                                <div class="col-md-6">
                                    <form method="post" action="listing.php?action=add&id=<?php echo $results->getProductId(); ?>"
                                        onsubmit= "return <?php echo json_encode($view->status)?>">
                                        <button type="submit" name="wishList" value="wishList" id="<?php echo $results->getProductId();?>" onclick="addToWatchList(this.id, <?php echo json_encode($view->status)?>)" class="addToList"><i class="fa fa-heart" aria-hidden="true"></i></button>
                                        <input type="hidden" name="price" value="<?php echo $results->getPrice()?>">
                                        <input type="hidden" name="title" value="<?php echo $results->getTitle()?>">
                                        <input type="hidden" name="size" value="<?php echo $results->getSize()?>">
                                        <input type="hidden" name="color" value="<?php echo $results->getColor()?>">
                                        <input type="hidden" name="image" value="<?php echo $results->getImg()?>">
                                        <input type="hidden" name="sellerID" value="<?php echo $results->getSellerId()?>">
                                        <input type="hidden" name="location" value="<?php echo $results->getCountry()?>">
                                        <input type="hidden" name="currency" value="<?php echo $results->getCurrency()?>">
                                        <?php if(isset($_SESSION['user_id'])){?>
                                            <input type="hidden" name="userID" value="<?php echo $_SESSION['user_id']?>">
                                        <?php } ?>
                                    </form>
                                   <div class="popUp show" >
                                      <span class="popupText" id="itemPopUp<?php echo $results->getProductId();?>">SignUp/LogIn to add to watchList</span>
                                   </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php } ?> <!--end of foreach loop-->
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <div class="row" id="searchBar">
                <form method="post" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>">
                    <div class=" form-group col-lg-12 searchCategory">
                        <input type="text" name="search" id="search" class="form-control" placeholder="Search">
                    </div>
                    <div class=" form-group col-lg-12 searchCategory">
                        <label for="category">Category</label>
                        <select id="category" name="category" class="form-control">
                            <option selected>Select Category</option>
                            <option>All</option>
                            <option>Jewelry</option>
                            <option>Accessory</option>
                            <option>Clothing</option>
                        </select>
                    </div>
                    <div class="form-group col-md-12 searchCategory">
                            <label for="location">Location(country)</label>
                            <select id="location" name="location" class="form-control">
                                <option selected>Select Country</option>
                                <option>All</option>
                                <option>Nigeria</option>
                                <option>Kenya</option>
                                <option>South Africa</option>
                                <option>Uganda</option>
                            </select>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-5">
                            <label for="minNo">MinPrice</label>
                            <input type="title" name="minNo" class="form-control" id="minNo">
                        </div>
                        <div class="vertical-center col-md-2">to</div>
                        <div class="form-group col-md-5">
                            <label for="maxNo">MaxPrice</label>
                            <input type="text" name="maxNo" class="form-control" id="maxNo">
                        </div>

                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="colorCategory">Color</label>
                            <select id="colorCategory" name="colorCategory" class="form-control">
                                <option selected>Colour</option>
                                <option>Black</option>
                                <option>White</option>
                                <option>Red</option>
                                <option>Green</option>
                                <option>Blue</option>
                                <option>Purple</option>
                                <option>Yellow</option>
                                <option>Brown</option>
                                <option>Gold</option>
                                <option>Pink</option>
                                <option>Indigo</option>
                                <option>Maroon</option>
                                <option>Grey</option>
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="title">Size</label>
                            <select id="sizeCategory" name="sizeCategory" class="form-control">
                                <option selected>Size</option>
                                <option>4</option>
                                <option>6</option>
                                <option>8</option>
                                <option>10</option>
                                <option>12</option>
                                <option>14</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <button type="submit" name="apply" id="apply" class="btn-lg btn-primary">Apply</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
    <?php echo $pagination->createLinks( $links, 'pagination pagination-sm' );?>

<?php require('template/footer.phtml') ?>