<?php require('template/header.phtml') ?>
<div class="container">
        <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
            <?php if (isset($_SESSION['errorM'])) : ?>
                <div class="bg-success lead text-center"><?php  echo $_SESSION['errorM'];
                    unset($_SESSION['errorM']) ?></div>
            <?php endif; ?>
            <div class="row listing">
            <?php  foreach ($view->results as $results){ ?>
                <div class="listing-card col-sm-4">
                    <div class="card">
                        <div class="card-block">
                            <img class="card-img-top" alt="Card image cap" src=images/<?php echo $results->getImg();?>>
                            <a href="aboutListing.php?item=<?php echo $results->getProductId();?>"><h3 class="card-title"><?php echo $results->getTitle();?></h3></a>
                            <p class="card-text"><?php echo $results->getDescription();?></p>
                            <div class="row">
                                <div class="col-md-6">
                                   <span class="price"><?php echo $results->getCurrency();?><?php echo $results->getPrice();?></span>
                                </div>
                                <div class="col-md-6">
                                    <form method="post" action="listing.php?action=add&id=<?php echo $results->getProductId(); ?>"
                                        onsubmit= "return <?php echo json_encode($view->status)?>">
                                        <button type="submit" name="wishList" value="wishList" id="<?php echo $results->getProductId();?>" onclick="addToWatchList(this.id, <?php echo json_encode($view->status)?>)" class="addToList"><i class="fa fa-heart" aria-hidden="true"></i></button>
                                        <input type="hidden" name="sellerID" value="<?php echo $results->getSellerId()?>">
                                        <?php if(isset($_SESSION['user_id'])){?>
                                            <input type="hidden" name="userID" value="<?php echo $_SESSION['user_id']?>">
                                        <?php } ?>
                                    </form>
                                   <div class="popUp show" >
                                      <span class="popupText" id="itemPopUp<?php echo $results->getProductId();?>">SignUp/LogIn to add to watchList</span>
                                   </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php } ?> <!--end of foreach loop-->
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <div class="row" id="searchBar">
                <form method="post" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>">
                    <div class=" form-group col-lg-12 searchCategory">
                        <input type="text" name="search" id="search" value="<?php if(isset($_POST['search'])){
                        echo htmlentities($_POST['search']);};?>" class="form-control" placeholder="Search">
                    </div>
                    <div class=" form-group col-lg-12 searchCategory">
                        <label for="category">Category</label>
                        <select id="category" name="category" class="form-control"  onchange="select(this.id, 'sizeCategory');">
                            <option value="">Select Category</option>
                            <option value="Jewellery"<?php if (isset($_POST['category']) && $_POST['category']== "Jewellery") echo "selected='selected'";?>>Jewellery</option>
                            <option value="Accessory"<?php if (isset($_POST['category']) && $_POST['category']== "Accessory") echo "selected='selected'";?>>Accessory</option>
                            <option value="Clothing"<?php if (isset($_POST['category']) && $_POST['category']== "Clothing") echo "selected='selected'";?>>Clothing</option>
                        </select>
                    </div>
                    <div class="form-group col-md-12 searchCategory">
                            <label for="location">Location(country)</label>
                            <select id="location" name="location" class="form-control">
                                <option value="">Select Country</option>
                                <option value="Nigeria"<?php if (isset($_POST['location']) && $_POST['location']== "Nigeria") echo "selected";?>>Nigeria</option>
                                <option value="Kenya"<?php if (isset($_POST['location']) && $_POST['location']== "Kenya") echo "selected='selected'";?>>Kenya</option>
                                <option value="South Africa"<?php if (isset($_POST['location']) && $_POST['location']== "South Africa") echo "selected='selected'";?>>South Africa</option>
                                <option value="Uganda"<?php if (isset($_POST['location']) && $_POST['location']== "Uganda") echo "selected='selected'";?>>Uganda</option>
                            </select>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-5">
                            <label for="minNo">MinPrice</label>
                            <input type="text" name="minNo" class="form-control" id="minNo"
                                   value="<?php if(isset($_POST['minNo'])){echo htmlentities($_POST['minNo']);};?>">
                        </div>
                        <div class="vertical-center col-md-2">to</div>
                        <div class="form-group col-md-5">
                            <label for="maxNo">MaxPrice</label>
                            <input type="text" name="maxNo" class="form-control" id="maxNo"
                              value="<?php if(isset($_POST['search'])){echo htmlentities($_POST['search']);};?>">
                        </div>

                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="colorCategory">Color</label>
                            <select id="colorCategory" name="colorCategory" class="form-control">
                                <option value="" selected>Colour</option>
                                <option value="Black">Black</option>
                                <option value="White">White</option>
                                <option value="Red">Red</option>
                                <option value="Green">Green</option>
                                <option value="Blue">Blue</option>
                                <option value="Purple">Purple</option>
                                <option value="Yellow">Yellow</option>
                                <option value="Brown">Brown</option>
                                <option value="Gold">Gold</option>
                                <option value="Pink">Pink</option>
                                <option value="Indigo">Indigo</option>
                                <option value="Maroon">Maroon</option>
                                <option value="Grey">Grey</option>
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="sizeCategory">Size</label>
                            <select id="sizeCategory" name="sizeCategory" class="form-control">
                                <option value="" selected>Size</option>
                                <option value= 4>4</option>
                                <option value= 6>6</option>
                                <option value= 8>8</option>
                                <option value= 10>10</option>
                                <option value= 12>12</option>
                                <option value=14>14</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <button type="submit" name="apply" id="apply" class="btn-lg btn-primary">Apply</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
    <?php echo $pagination->createLinks( $links, 'pagination pagination-sm' );?>

<?php require('template/footer.phtml') ?>