<?php require('template/header.phtml') ?>
<?php if (isset($_SESSION['message'])) : ?>
    <div class="bg-success lead text-center"><?php  echo $_SESSION['message'];
        unset($_SESSION['message']) ?></div>
<?php endif; ?>
    <form method="post" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>">
        <div class="container form">
            <h4 class="formHeader">ACCESS YOR ACCOUNT</h4>
            <hr>
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label for="emailInput">Email</label>
                    <input type="email" class="form-control" id="emailInput" name="emailInput" placeholder="Email">
                </div>
                <div class="form-group col-md-12">
                    <label for="inputPwd">Password</label>
                    <input type="password" class="form-control" id="inputPwd" name="inputPwd" placeholder="Password">
                </div>
                <div class="form-group col-md-12">
                    <input type="text" class="form-control" name="captcha">

                </div>
            </div>
           <!--<div class="form-group col-md-12">
                <div class="form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" type="checkbox" name="checkBox"> Remember Me
                    </label>
                </div>
            </div>-->
            <div class="form-group col-md-12">
                <button type="submit" name="loginBtn" class="btn-lg btn-success">Login</button>
            </div>
            <hr>
            <div class="col-md-12">
                <a href="register.php">Register a free account</a>
            </div>

        </div>
    </form>


<?php require('template/footer.phtml') ?>