<?php require('template/header.phtml') ?>
<?php if (isset($_SESSION['login']))  unset($_SESSION['login']); ?>

    <form method="post" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>" id="loginForm">
        <div id="errorM" class="bg-danger lead text-center"></div>
        <div class="container form">
            <h4 class="formHeader">ACCESS YOUR ACCOUNT</h4>
            <hr>
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label for="emailInput">Email</label>
                    <input type="email" class="form-control" id="emailInput" name="emailInput" autocomplete="off"
                           value="<?php if(isset($_SESSION['login'])){extract($_SESSION['login']); echo $email;}   ?>" placeholder="Email" required>
                </div>
                <div class="form-group col-md-12">
                    <label for="inputPwd">Password</label>
                    <input type="password" class="form-control" id="inputPwd" name="inputPwd"
                           value="<?php if(isset($_SESSION['login'])){extract($_SESSION['login']); echo $pwd;}  ?>" autocomplete="off" placeholder="Password" required>
                </div>
            </div>
            <div class="form-group col-md-12">
                <input type="submit" value="Submit" name="loginBtn" id="loginBtn" class="btn-lg btn-success">
                <input type="hidden" id="token" name="token" value=" <?php if(isset($_SESSION['token'])) echo $_SESSION['token']?>">
            </div>
            <hr>
            <div class="col-md-12">
                <a href="register.php">Register a free account</a>
            </div>

        </div>

    </form>


<?php require('template/footer.phtml') ?>