<?php require('template/header.phtml') ?>
<?php if (isset($_SESSION['adMessage'])) : ?>
    <div class="bg-danger lead text-center"><?php  echo $_SESSION['adMessage'];
        unset($_SESSION['adMessage'])?></div>
<?php endif; ?>
    <div id="successM" class="bg-danger lead text-center"></div>
    <form id="placeAdForm" name="placeAdForm" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>" method="post" enctype="multipart/form-data">
       <div id="errorM" class="bg-danger lead text-center"></div>
        <div class="container form">
            <h4 class="formHeader">PUBLISH A LISTING</h4>
            <hr>
            <div id="headerPlaceAd" class="form-group col-md-12">
                <div class="form-group col-md-6">
                    <h3>General Information</h3>
                </div>
                <div class="form-group col-md-6">
                    <label class="adDate" for="date">Date:</label>
                    <?php echo "<span class='adDate'>" .date('l jS \of F Y')."</span>"?>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="category">Categories</label>
                    <select id="category" name="category" class="form-control">
                        <option selected>Choose Category</option>
                        <option>Clothing</option>
                        <option>Jewellery</option>
                        <option>Accessory</option>
                    </select>
                </div>
                <div id="titleDiv" class="form-group col-md-6">
                    <label for="title">Title</label>
                        <input type="text" name="title" class="form-control" id="title" required>
                        <ul class="formConstraint">
                            <li>No html special characters input</li>
                        </ul>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label for="description">Description</label>
                    <textarea name="description" class="form-control" id="description" required></textarea>
                </div>
            </div>
            <div class="form-row">
                <div id="priceDiv" class="form-group col-md-4">
                    <label for="amount">Price(£)</label>
                    <!--<div class="input-group">
                        <!--<span class="input-group-addon">&pound;</span>-->
                        <input id="amount" name="amount" type="text" class="form-control" required>
                        <ul class="formConstraint">
                            <li>Enter price as a number</li>
                            <li>No special characters allowed</li>
                        </ul>
                </div>
                <div class="form-group col-md-4">
                    <label for="color">Color</label>
                    <select id="color" name="color" class="form-control" required>
                        <option selected>Black</option>
                        <option>White</option>
                        <option>Red</option>
                        <option>Green</option>
                        <option>Blue</option>
                        <option>Purple</option>
                        <option>Yellow</option>
                        <option>Brown</option>
                        <option>Gold</option>
                        <option>Pink</option>
                        <option>Indigo</option>
                        <option>Maroon</option>
                        <option>Grey</option>
                        <option>Multicolored</option>
                    </select>
                </div>
                <div class="form-group col-md-4">
                    <label for="size">Size</label>
                    <select id="size" name="size" class="form-control" required>
                        <option selected>4</option>
                        <option>6</option>
                        <option>8</option>
                        <option>10</option>
                        <option>12</option>
                        <option>14</option>
                    </select>
                </div>
            </div>
            <div id="fileDiv" class="form-group col-md-12">
                <label for="file">Upload Picture</label>
                <input id="file" name="file" type="file" class="uploadPicture file" required>
                <img src="" id="previewImg" height="200" alt="Image preview">
            </div>
            <div class="col-md-12">
                <hr>
                <h3>Seller Information</h3>
                <hr>
            </div>
            <?php if(isset($_SESSION["logged_in"]) && $_SESSION["logged_in"] == true ){
                echo '<div class="form-row">
                <div class="form-group col-md-4">
                    <label for="sellerName">Name</label>
                    <p>'.$_SESSION['fullName'].'</p>
                </div>
                <div class="form-group col-md-4">
                    <label for="sellerEmail">Email</label>
                     <p>'.$_SESSION['email'].'</p>
                </div>
                <div class="form-group col-md-4">
                    <label for="sellerLocation">Location</label>
                     <p>'.$_SESSION['country'].', '.$_SESSION['state'].'</p>
                </div>
            </div>';

            }
            ?>
            <div class="form-group col-md-12">
                <input type="submit" id="publish" value="Publish" name="publish" class="btn-lg btn-success">
                <input type="hidden" id="token" name="token" value=" <?php echo $_SESSION['token']?>">
            </div>

        </div>
    </form>

<?php require('template/footer.phtml') ?>