<?php require('template/header.phtml') ?>
<?php if (isset($_SESSION['adMessage'])) : ?>
    <div class="bg-danger lead text-center"><?php  echo $_SESSION['adMessage'];
        unset($_SESSION['adMessage'])?></div>
<?php endif; ?>
    <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>" method="post" enctype="multipart/form-data">
        <div class="container form">
            <h4 class="formHeader">PUBLISH A LISTING</h4>
            <hr>
            <h3>General Information</h3>
            <hr>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="category">Categories</label>
                    <select id="category" name="category" class="form-control" onchange="select(this.id, 'size');">
                        <option selected>Clothing</option>
                        <option>Jewellery</option>
                        <option>Accessory</option>
                    </select>
                </div>
                <div class="form-group col-md-6">
                    <label for="title">Title</label>
                    <input type="title" name="title" class="form-control" id="title">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label for="description">Description</label>
                    <textarea type="text" name="description" class="form-control" id="description"></textarea>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-2">
                    <label for="currency">Currency</label>
                    <select id="currency" name="currency" class="form-control">
                        <option selected>&#8358;</option>
                        <option>KSh</option>
                        <option>R</option>
                        <option>USh</option>
                    </select>
                </div>
                <div class="form-group col-md-6">
                    <label for="amount">Price</label>
                    <input id="amount" name="amount" type="number" class="form-control">
                </div>
                <div class="form-group col-md-2">
                    <label for="color">Color</label>
                    <select id="color" name="color" class="form-control">
                        <option selected>Black</option>
                        <option>White</option>
                        <option>Red</option>
                        <option>Green</option>
                        <option>Blue</option>
                        <option>Purple</option>
                        <option>Yellow</option>
                        <option>Brown</option>
                        <option>Gold</option>
                        <option>Pink</option>
                        <option>Indigo</option>
                        <option>Maroon</option>
                        <option>Grey</option>
                        <option>Multicolored</option>
                    </select>
                </div>
                <div class="form-group col-md-2">
                    <label for="size">Size</label>
                    <select type="number" id="size" name="size" class="form-control">
                        <option selected>4</option>
                        <option>6</option>
                        <option>8</option>
                        <option>10</option>
                        <option>12</option>
                        <option>14</option>
                    </select>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label for="date">Date</label>
                <input id="date" name="date" type="date" class="form-control">
            </div>
            <div class="form-group col-md-6">
                <label for="file">Upload Picture</label>
                <input id="file" name="file" type="file" class="uploadPicture file">
            </div>
            <div class="col-md-12">
                <hr>
                <h3>Listing Location</h3>
                <hr>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="country">Country</label>
                    <select id="country" name="country" class="form-control" onchange="printState(this.id, 'state');">
                        <option value ="" selected>Select Country</option>
                        <option value="Nigeria">Nigeria</option>
                        <option value="Kenya">Kenya</option>
                        <option value="South Africa">South Africa</option>
                        <option value="Uganda">Uganda</option>
                    </select>
                </div>
                <div class="form-group col-md-6">
                    <label for="state">State</label>
                    <select id="state" name="state" class="form-control">
                        <<option value ="" selected>Select State</option>
                    </select>
                </div>
            </div>
            <div class="col-md-12">
                <hr>
                <h3>Seller Information</h3>
                <hr>
            </div>
            <?php if(isset($_SESSION["logged_in"]) && $_SESSION["logged_in"] == true ){
                echo '<div class="form-row">
                <div class="form-group col-md-6">
                    <label for="sellerName">Name</label>
                    <p>'.$_SESSION['firstName'].'</p>
                </div>
                <div class="form-group col-md-6">
                    <label for="sellerEmail">Email</label>
                     <p>'.$_SESSION['email'].'</p>
                </div>
            </div>';

            }
            else{
                echo ' <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="sellerName">Name</label>
                    <input type="text" name="sellerName" class="form-control" id="sellerName">
                </div>
                <div class="form-group col-md-6">
                    <label for="sellerEmail">Email</label>
                    <input type="email" name="sellerEmail" class="form-control" id="sellerEmail">
                </div>
            </div>';
            }

            ?>
            <div class="form-group col-md-12">
                <button type="submit" name="publish" class="btn-lg btn-success">Publish</button>
            </div>

        </div>
    </form>

<?php require('template/footer.phtml') ?>