<?php require('template/header.phtml') ?>
<?php if (isset($_SESSION['message'])) : ?>
    <div class="bg-danger lead text-center"><?php  echo $_SESSION['message'];
    unset($_SESSION['message'])?></div>
    <?php endif; ?>

  <form method="post" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>" onsubmit="return validate()" name="regForm">
     <div class="container form">
            <h4 class="formHeader">REGISTER TO CONTACT SELLERS AND PURCHASE ITEMS</h4>
        <hr>
         <div class="form-row">
             <div class="form-group col-md-6" id="firstName-div">
                 <label for="name">Firstname</label>
                 <input type="text" name="firstName" class="form-control" id="name" placeholder="FirstName">
             </div>
             <div class="form-group col-md-6"  id="surName-div">
                 <label for="surName">Surname</label>
                 <input type="text" name="surName" class="form-control" id="surName" placeholder="SurName">
             </div>
         </div>
        <div class="form-row">
            <div class="form-group col-md-6" id="email-div">
                <label for="email">Email</label>
                <input type="Email" name ="email" class="form-control" id="email" placeholder="Email">
            </div>
            <div class="form-group col-md-6"  id="password-div">
                <label for="password">Password</label>
                <input type="Password" name= "password" class="form-control" id="password" placeholder="Password">
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-12"  id="address1-div">
                    <label for="inputAddress1">Address</label>
                    <input type="Text" name ="addressLine1" class="form-control" id="inputAddress1" placeholder="Blk B Flat 1">
            </div>
            <div class="form-group col-md-12"  id="address2-div">
                    <label for="inputAddress2">Address 2</label>
                    <input type="Text" name ="addressLine2" class="form-control" id="inputAddress2" placeholder="Defence Quarters">
            </div>
        </div>
        <div class="form-row"">
            <div class="form-group col-md-4"  id="country-div">
                <label for="country">Country</label>
                <select id="country" name="country" class="form-control" onchange="printState(this.id, 'state');">
                    <option value ="" selected>Select Country</option>
                    <option value="Nigeria">Nigeria</option>
                    <option value="Kenya">Kenya</option>
                    <option value="South Africa">South Africa</option>
                    <option value="Uganda">Uganda</option>
                </select>
            </div>
            <div class="form-group col-md-4"  id="state-div">
                <label for="state">State</label>
                <select id="state" name="state" class="form-control">
                    <option value ="" selected>Select State</option>
                </select>
            </div>
            <div class="form-group col-md-4" id="number-div">
                <label for="phoneNumber">PhoneNumber</label>
                <input type="text" id="phoneNumber" name="phoneNumber" class="form-control">
            </div>
        </div>
         <div class="form-group col-md-12">
             <button type="submit" name="register" class="btn-lg btn-success">Register</button>
         </div>

    </div>
  </form>


<?php require('template/footer.phtml') ?>