    </div>


    <footer class="footer">
        <div class="row" id="footerContent">
            <div class="col-lg-3 col-md-4 col-sm-12 col-xs-12">
                <h4 class="bottomList">Steps</h4>
                <ul class="bottomlink">
                    <li><a href="#">Help</a></li>
                    <li><a href="#">Contact Us</a></li>
                    <li><a href="placeAd.php">Place Ad for Free</a></li>
                </ul>
            </div>
            <div class="col-lg-6 col-md-4 col-sm-12 col-xs-12">
                <h4 class="bottomList" id="headerSocialM">Stay Connected</h4>
                <div id="socialMedia">
                    <a href="#" class="fa fa-facebook footerIcon"></a>
                    <a href="#" class="fa fa-twitter footerIcon"></a>
                    <a href="#" class="fa fa-google footerIcon"></a>
                    <a href="#" class="fa fa-linkedin footerIcon"></a>
                    <a href="#" class="fa fa-youtube footerIcon"></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-12 col-xs-12">
                <h4 class="bottomList">Address</h4>
                <address>
                    Contact by <a href="mailto:webmaster@example.com">contact@mallfromAfrica.org.uk</a>.<br>
                    Visit us at:<br>
                    26 Gerald Rd<br>
                    M6 6DN
                </address>
            </div>
        </div>
    </footer>
<!-- Bootstrap core JavaScript-->
<!--================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript" src="js/scripts.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>