<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme-->
    <link href="css/bootstrap-theme.css" rel="stylesheet">
    <link href="css/my-style.css" rel="stylesheet">
    <!--Font awesome-->
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

    <title>MallFromAfrica <?php echo $view->pageTitle; ?></title>
</head>

<body role="document">
        <nav class="navbar">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="index.php"><img src="images/logo.png"></a>
                </div>
                <div class="bars">
                    <button type="button" class="navbar-collapse" data-toggle="collapse"
                            data-target="#MyNavbar" aria-controls="MyNavbar" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fa fa-bars fa-lg"></i>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="MyNavbar">
                    <ul class="nav navbar-nav navbar-right">
                        <?php
                        if(isset($_SESSION["logged_in"]) && $_SESSION["logged_in"] == true ){
                            if(isset($_SESSION["userRole"]) && $_SESSION['userRole'] === "admin-true"){
                                echo "<li><div id='userName'>Hi ".$_SESSION['firstName']."</div></li>
                                        <li><a href='listing.php'>Listings</a></li>
                                       <li><a href='index.php?action=logout'>Logout</a></li>";
                            }else{
                                echo "<li><div id='userName'>Hi ".$_SESSION['firstName']."</div></li>
                                <li class='active'><a href='index.php'>Home</a></li>
                                <li><a href='listing.php'>Listings</a></li>
                                <li><a href='userAccount.php'>My Account</a></li>
                                <li><a href='index.php?action=logout'>Logout</a></li>";
                            }
                        }else{
                            echo "<li class='active'><a href='index.php'>Home</a></li>
                                  <li><a href='listing.php'>Listings</a></li>
                                  <li><a href='login.php'>Login</a></li>
                                  <li><a href='register.php'>Register</a></li>";
                        }

                        ?>
                    </ul>
                </div>

            </div>
        </nav>
        <?php if($_SESSION['userRole'] === "admin-true"):?>
            <!--hide jumbotron-->

        <?php else:?>
            <div class="jumbotron jumbotron-fluid">
                <div class="container" id="jumbotronInfo">
                    <h1 class="display-3">Africa To Uk</h1>
                    <p class="lead">The site that accommodates adverts directly from Africa and delivers to your door step
                        in the UK.</p>

                    <a href="placeAd.php"><button class="btn btn-primary">Place Free Ad</button></a>
                </div>
            </div>
        <?php endif;?>


    <div class="container-fluid">



